// flow-typed signature: 7be037a7d8ae87deabb1015ce0282ba0
// flow-typed version: <<STUB>>/bs-json_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-json/lib/js/__tests__/json_decode_test' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/__tests__/json_encode_test' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/examples/complex' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/examples/decode' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/examples/encode' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/examples/parse' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/src/json_decode' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/src/json_encode' {
  declare module.exports: any;
}

declare module 'bs-json/lib/js/src/json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-json/lib/js/__tests__/json_decode_test.js' {
  declare module.exports: $Exports<'bs-json/lib/js/__tests__/json_decode_test'>;
}
declare module 'bs-json/lib/js/__tests__/json_encode_test.js' {
  declare module.exports: $Exports<'bs-json/lib/js/__tests__/json_encode_test'>;
}
declare module 'bs-json/lib/js/examples/complex.js' {
  declare module.exports: $Exports<'bs-json/lib/js/examples/complex'>;
}
declare module 'bs-json/lib/js/examples/decode.js' {
  declare module.exports: $Exports<'bs-json/lib/js/examples/decode'>;
}
declare module 'bs-json/lib/js/examples/encode.js' {
  declare module.exports: $Exports<'bs-json/lib/js/examples/encode'>;
}
declare module 'bs-json/lib/js/examples/parse.js' {
  declare module.exports: $Exports<'bs-json/lib/js/examples/parse'>;
}
declare module 'bs-json/lib/js/src/json_decode.js' {
  declare module.exports: $Exports<'bs-json/lib/js/src/json_decode'>;
}
declare module 'bs-json/lib/js/src/json_encode.js' {
  declare module.exports: $Exports<'bs-json/lib/js/src/json_encode'>;
}
declare module 'bs-json/lib/js/src/json.js' {
  declare module.exports: $Exports<'bs-json/lib/js/src/json'>;
}
