// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Random = require("./Random.js");
var Discord = require("./Discord.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var eightBallResults = /* array */[
  /* tuple */[
    /* Affirmative */0,
    "It is certain"
  ],
  /* tuple */[
    /* Affirmative */0,
    "It is decidedly so"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Without a doubt"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Yes definitely"
  ],
  /* tuple */[
    /* Affirmative */0,
    "You may rely on it"
  ],
  /* tuple */[
    /* Affirmative */0,
    "As I see it, yes"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Most likely"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Outlook good"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Yes"
  ],
  /* tuple */[
    /* Affirmative */0,
    "Signs point to yes"
  ],
  /* tuple */[
    /* Noncommittal */1,
    "Reply hazy try again"
  ],
  /* tuple */[
    /* Noncommittal */1,
    "Ask again later"
  ],
  /* tuple */[
    /* Noncommittal */1,
    "Better not tell you now"
  ],
  /* tuple */[
    /* Noncommittal */1,
    "Cannot predict now"
  ],
  /* tuple */[
    /* Noncommittal */1,
    "Concentrate and ask again"
  ],
  /* tuple */[
    /* Negative */2,
    "Don't count on it"
  ],
  /* tuple */[
    /* Negative */2,
    "My reply is no"
  ],
  /* tuple */[
    /* Negative */2,
    "My sources say no"
  ],
  /* tuple */[
    /* Negative */2,
    "Outlook not so good"
  ],
  /* tuple */[
    /* Negative */2,
    "Very doubtful"
  ]
];

function handle(engine, msg) {
  var match = Belt_Option.getExn(Random.pick(/* None */0, /* None */0, eightBallResults, engine));
  var tmp;
  switch (match[0]) {
    case 0 : 
        tmp = ":+1:";
        break;
    case 1 : 
        tmp = ":shrug:";
        break;
    case 2 : 
        tmp = ":-1:";
        break;
    
  }
  Discord.Message[/* reply */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, match[1] + (" " + tmp), msg);
  return /* () */0;
}

exports.eightBallResults = eightBallResults;
exports.handle = handle;
/* Random Not a pure module */
