// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Random = require("./Random.js");

function search(query, client) {
  return client.search({
              q: query
            });
}

function getRandomUrl(searchResults, engine) {
  var match = Random.pick(/* None */0, /* None */0, searchResults.data, engine);
  if (match) {
    return match[0].url;
  } else {
    return "";
  }
}

function random(tag, client) {
  return client.random(tag).then((function (response) {
                return Promise.resolve(response.data.url);
              }));
}

exports.search = search;
exports.getRandomUrl = getRandomUrl;
exports.random = random;
/* Random Not a pure module */
