// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var $$Array    = require("bs-platform/lib/js/array.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function encodePresenceStatus(x) {
  switch (x) {
    case 0 : 
        return "online";
    case 1 : 
        return "idle";
    case 2 : 
        return "invisible";
    case 3 : 
        return "dnd";
    
  }
}

var Guild = /* module */[];

function asDMChannel(channel) {
  var match = channel.type;
  if (match === "dm") {
    return /* Some */[channel];
  } else {
    return /* None */0;
  }
}

function asTextChannel(channel) {
  var match = channel.type;
  if (match === "text") {
    return /* Some */[channel];
  } else {
    return /* None */0;
  }
}

var Channel = /* module */[
  /* asDMChannel */asDMChannel,
  /* asTextChannel */asTextChannel
];

var DMChannel = /* module */[];

var TextChannel = /* module */[];

var User = /* module */[];

function reply($staropt$star, content, message) {
  var split = $staropt$star ? $staropt$star[0] : /* false */0;
  return message.reply(content, {
              split: Js_boolean.to_js_boolean(split)
            });
}

function replyMultiline($staropt$star, content, message) {
  var split = $staropt$star ? $staropt$star[0] : /* true */1;
  return message.reply($$Array.of_list(content), {
              split: Js_boolean.to_js_boolean(split)
            });
}

var Message = /* module */[
  /* reply */reply,
  /* replyMultiline */replyMultiline
];

function setPresence($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, user) {
  var status = $staropt$star ? $staropt$star[0] : /* Online */0;
  var afk = $staropt$star$1 ? $staropt$star$1[0] : /* false */0;
  var game = $staropt$star$2 ? $staropt$star$2[0] : "";
  var gameUrl = $staropt$star$3 ? $staropt$star$3[0] : "";
  return user.setPresence({
              status: encodePresenceStatus(status),
              afk: Js_boolean.to_js_boolean(afk),
              game: {
                name: game,
                url: gameUrl
              }
            });
}

var ClientUser = /* module */[/* setPresence */setPresence];

var Client = /* module */[];

exports.encodePresenceStatus = encodePresenceStatus;
exports.Guild                = Guild;
exports.Channel              = Channel;
exports.DMChannel            = DMChannel;
exports.TextChannel          = TextChannel;
exports.User                 = User;
exports.Message              = Message;
exports.ClientUser           = ClientUser;
exports.Client               = Client;
/* No side effect */
