// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Fs           = require("fs");
var Curry        = require("bs-platform/lib/js/curry.js");
var Utils        = require("./utils.js");
var Js_exn       = require("bs-platform/lib/js/js_exn.js");
var Js_dict      = require("bs-platform/lib/js/js_dict.js");
var Js_json      = require("bs-platform/lib/js/js_json.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function getAll() {
  var content;
  try {
    content = Fs.readFileSync("./state.json", "utf8");
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      content = Utils.Option[/* orRaise */14](exn, Utils.Option[/* mapTo */6]("")(Utils.Option[/* filter */10]((function (code) {
                        return +(code === "ENOENT");
                      }))(Utils.exnCode(exn[1]))));
    } else {
      throw exn;
    }
  }
  var tmp;
  try {
    tmp = JSON.parse(content);
  }
  catch (exn$1){
    tmp = JSON.parse("{}");
  }
  var json = Js_json.classify(tmp);
  var tmp$1;
  tmp$1 = typeof json === "number" || json.tag !== 2 ? /* None */0 : /* Some */[json[0]];
  return Utils.Option[/* value */8]({ }, tmp$1);
}

var getAll$1 = Utils.memoize(getAll);

function getForSnowflake(snowflake) {
  return Js_primitive.undefined_to_opt(getAll$1(/* () */0)[snowflake]);
}

var unsafeDeleteKey = (function(a,b){return(delete a[b],0)});

function setForSnowflake(snowflake, value) {
  var state = getAll$1(/* () */0);
  var stringifiedValue = JSON.stringify(value);
  if (stringifiedValue !== undefined) {
    state[snowflake] = JSON.parse(stringifiedValue);
  } else {
    Curry._2(unsafeDeleteKey, state, snowflake);
  }
  Fs.writeFileSync("./state.json", JSON.stringify(state), "utf8");
  return /* () */0;
}

function StateAccessor(T) {
  var get = function (t) {
    return Curry._1(T[/* decode */1], getForSnowflake(Curry._1(T[/* getSnowflake */2], t)));
  };
  var set = function (t, state) {
    return setForSnowflake(Curry._1(T[/* getSnowflake */2], t), Curry._1(T[/* encode */0], state));
  };
  var update = function (t, updater) {
    return set(t, Curry._1(updater, get(t)));
  };
  return /* module */[
          /* get */get,
          /* set */set,
          /* update */update
        ];
}

function encode(userState) {
  return Js_dict.fromArray(/* array */[
              /* tuple */[
                "note",
                userState[/* note */0]
              ],
              /* tuple */[
                "rolls",
                userState[/* rolls */1]
              ]
            ]);
}

function get(t) {
  var userState = getForSnowflake(t.id);
  var dict = Utils.Option[/* value */8]({ }, Utils.Option[/* bind */3](Js_json.decodeObject, userState));
  return /* record */[
          /* note */Utils.Option[/* value */8]("", Utils.Option[/* bind */3](Js_json.decodeString, Js_primitive.undefined_to_opt(dict["note"]))),
          /* rolls */Utils.Option[/* value */8](0.0, Utils.Option[/* bind */3](Js_json.decodeNumber, Js_primitive.undefined_to_opt(dict["rolls"]))) | 0
        ];
}

function set(t, state) {
  return setForSnowflake(t.id, encode(state));
}

function update(t, updater) {
  return set(t, Curry._1(updater, get(t)));
}

var UserState = /* module */[
  /* get */get,
  /* set */set,
  /* update */update
];

exports.getAll          = getAll$1;
exports.getForSnowflake = getForSnowflake;
exports.unsafeDeleteKey = unsafeDeleteKey;
exports.setForSnowflake = setForSnowflake;
exports.StateAccessor   = StateAccessor;
exports.UserState       = UserState;
/* getAll Not a pure module */
